package main.java.gui;

import main.java.pedestriansimulator.ApplicationSingletone;

/**
 * On this Panel, the user can choose some settings about the displayed graphic
 */
public class GUISettings extends javax.swing.JPanel {

    //Settings
    public boolean showVisibleLines;
    public boolean showLineToTarget;
    public boolean showConvexHull;
    public boolean showPreferredRadius;
    public boolean showDebug;
    public boolean show3DEffect;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jConvexH;
    private javax.swing.JToggleButton jToGoal;
    private javax.swing.JToggleButton jToWalls;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;

    /**
     * Creates new form GUISettings
     */
    public GUISettings() {
        //set the default values
        initComponents();
        showVisibleLines = false;
        showLineToTarget = true;
        jToGoal.setSelected(true);
        showConvexHull = true;
        jConvexH.setSelected(true);
        show3DEffect = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        jToWalls = new javax.swing.JToggleButton();
        jToGoal = new javax.swing.JToggleButton();
        jConvexH = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(100, 39));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jToWalls.setText("Show visible lines");
        jToWalls.addActionListener(evt -> jToWallsActionPerformed());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jToWalls, gridBagConstraints);

        jToGoal.setText("Hide path");
        jToGoal.addActionListener(evt -> jToGoalActionPerformed());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jToGoal, gridBagConstraints);

        jConvexH.setText("Show convex hull");
        jConvexH.addActionListener(evt -> jConvexHActionPerformed());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jConvexH, gridBagConstraints);

        jToggleButton3.setText("Show preferred space");
        jToggleButton3.addActionListener(evt -> jToggleButton3ActionPerformed());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jToggleButton3, gridBagConstraints);

        jToggleButton2.setText("Show debug information");
        jToggleButton2.addActionListener(evt -> jToggleButton2ActionPerformed());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jToggleButton2, gridBagConstraints);

        jToggleButton4.setText("Show 3D walls (test)");
        jToggleButton4.addActionListener(evt -> jToggleButton4ActionPerformed());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jToggleButton4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jToWallsActionPerformed() {//GEN-FIRST:event_jToWallsActionPerformed
        //switch the value of 'showVisibleLines'
        showVisibleLines = jToWalls.isSelected();
        ApplicationSingletone.getCurrentMap().change();
        //Update button title
        if (showVisibleLines) {
            jToWalls.setText("Show visible lines");
        } else {
            jToWalls.setText("Show visible lines");
        }
    }//GEN-LAST:event_jToWallsActionPerformed

    private void jToGoalActionPerformed() {//GEN-FIRST:event_jToGoalActionPerformed
        //switch the value of 'showLineToTarget'
        showLineToTarget = jToGoal.isSelected();
        ApplicationSingletone.getCurrentMap().change();
        if (showLineToTarget) {
            //Update button title

            jToGoal.setText("Hide path");
        } else {
            jToGoal.setText("Show path");
        }
    }//GEN-LAST:event_jToGoalActionPerformed

    private void jConvexHActionPerformed() {//GEN-FIRST:event_jConvexHActionPerformed
        //switch the value of 'showConvexHull'
        showConvexHull = jConvexH.isSelected();
        ApplicationSingletone.getCurrentMap().change();
        if (showConvexHull) {
            //Update button title

            jConvexH.setText("Hide convex hull");
        } else {
            jConvexH.setText("Show convex hull");
        }
    }//GEN-LAST:event_jConvexHActionPerformed

    private void jToggleButton3ActionPerformed() {//GEN-FIRST:event_jToggleButton3ActionPerformed
        //switch the value of 'showPreferredRadius'
        showPreferredRadius = jToggleButton3.isSelected();
        ApplicationSingletone.getCurrentMap().change();
        if (showPreferredRadius) {
            //Update button title

            jToggleButton3.setText("Hide preferred space");
        } else {
            jToggleButton3.setText("Show preferred space");
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed() {//GEN-FIRST:event_jToggleButton2ActionPerformed
        //switch the value of 'showDebug'
        showDebug = jToggleButton2.isSelected();
        ApplicationSingletone.getCurrentMap().change();
        if (showDebug) {
            //Update button title

            jToggleButton2.setText("Hide debug information");
        } else {
            jToggleButton2.setText("Show debug information");
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed() {//GEN-FIRST:event_jToggleButton4ActionPerformed
        //switch the value of 'show3DEffect'
        show3DEffect = jToggleButton4.isSelected();
        ApplicationSingletone.getCurrentMap().change();
        if (show3DEffect) {
            //Update button title

            jToggleButton4.setText("Hide 3D walls (test)");
        } else {
            jToggleButton4.setText("Show 3D walls (test)");
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed
    // End of variables declaration//GEN-END:variables
}
